### ISSUE TITLE
404(访问127.0.0.1:65472)排查思路

### ISSUE THREAD

**Issue by SY-LG** [1357310795/JboxWebdav#10]
### 🐛 问题描述(Description)

许久未打开后报错，从源头排查发现在`验证可用性&下一步`已经出现问题。由于水源最近也没人反馈，判断为本地环境问题。

如标题所言，浏览器访问监听端口报404，目前已进行以下排查，未发现线索。请求指导排查思路：

- 不同时间多次测试
- 重启后将所有多余进程结束（防火墙、杀软、clash等）
- 其余端口似乎不存在问题（用streamlit写了个hello，8501端口可正常访问）

### 📄 日志信息(Log Information)

webdav似乎没有单独的日志文件，控制台输出如下

```
Welcome to JboxWebdav!
尝试登录...
Cookie登录成功。
WebDAV 服务器运行中。按下 x 退出，按下 c 进入设置。
监听地址：http://127.0.0.1:65472/
WebDavDispatcher - Info - GET:http://127.0.0.1:65472/:127.0.0.1:65472 - Start processing
JboxStore - Debug - 【】路径 http://127.0.0.1:65472/
WebDavDispatcher - Info - GET:http://127.0.0.1:65472/:127.0.0.1:65472 - Finished processing (50ms, HTTP result: 404)
```

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 1.1（使用release中最新的`懒得改版本号（`登录失败报403，暂且不管）
- 系统版本号(OS Version):  例如 Windows 10.19045.3448

**Comment by 1357310795** [comment]
所以webdav功能好用吗
访问
```
http://127.0.0.1:65472/你网盘根目录下的随便一个文件名
```
看看

**Comment by SY-LG** [comment]
不太行，还是404

**Comment by 1357310795** [comment]
那就重新登录一下吧（
cookie应该在 `%APPDATA%/jboxwebdav` 下面

**Comment by SY-LG** [comment]
`The remote server returned an error: (403) .`，登录失败

**Comment by 1357310795** [comment]
哦想起来了，好像要用actions里的最新版本

https://github.com/1357310795/JboxWebdav/actions/runs/6130292153

***
新云盘马上上线了，这个程序预计不再维护。

**Comment by SY-LG** [comment]
搞定了，感谢teru老师。期待新云盘！
