### ISSUE TITLE
无法登录，403

### ISSUE THREAD

**Issue by stargazerZJ** [1357310795/JboxWebdav#12]
我认为应该是最近jac登录ui的uuid格式变化导致的。
推荐提取方式`uuid = re.search(r'uuid: "([0-9a-f-]+)"', r.text).group(1)`

**Comment by 1357310795** [comment]
这个项目里没用二维码登录，不受影响。

403 的问题有待调查，现在 Actions 里的最新版本可以用，多试几次。
