### ISSUE TITLE
持久化设置选项

### ISSUE THREAD

**Issue by ShenJiahuan** [1357310795/JboxWebdav#3]
### 🥰 需求描述(Description)

监听地址、停用/启用“交大空间”、停用/启用“他人的分享链接”这三个设置似乎没有做持久化，导致每次启动需要重新设置

### 🧐 解决方案(Solution)

持久化到一个yaml文件，每次启动从文件读配置

**Comment by 1357310795** [comment]
控制台应用因为要考虑跨平台，这个暂时还没做，很快会补上。

WPF 和 MAUI 的应用都是有保存设置的。

**Comment by 1357310795** [comment]
https://github.com/1357310795/JboxWebdav/releases/tag/v0.11

https://1357310795.github.io/JboxWebdav/tip/Config.html
