### ISSUE TITLE
.NET版本问题

### ISSUE THREAD

**Issue by mrpl327** [1357310795/JboxWebdav#6]
下载的.NET版本是6.0.9，然后运行软件提示错误
![image](https://user-images.githubusercontent.com/58623660/191047770-249975b2-73ab-4b30-bbe2-41dcea372a08.png)
这是需要下载对应版本的.NET框架吗？

**Comment by 1357310795** [comment]
理论上是兼容的

是不是32位和64位搞错了
***
点“是”进去再下载安装一下吧，准没错

**Comment by mrpl327** [comment]
换下了6.0.0竟然还有这个问题...点了是之后没有反应（点了好多次），是不是电脑的问题

**Comment by 1357310795** [comment]
> 换下了6.0.0竟然还有这个问题...点了是之后没有反应（点了好多次），是不是电脑的问题

确定下载正确了？桌面应用x64

![image](https://user-images.githubusercontent.com/35869804/191051280-95745dd6-9bb8-4aea-9552-d84830cfb318.png)

**Comment by mrpl327** [comment]
我的问题...竟然下载成了控制台应用

**Comment by 1357310795** [comment]
哈哈，文档上还给“运行桌面应用”加粗了来着😂
