### ISSUE TITLE
localhost可访问端口，分配的IP地址不可访问

### ISSUE THREAD

**Issue by APORduo** [1357310795/JboxWebdav#9]
### 🐛 问题描述(Description)

在本机浏览器内输入 `127.0.0.1:65472` 可访问到端口，`分配ip:65472`不可访问。

### 🎨 预期行为(Expected Behavior)

将服务挂载到校园内某一主机实现服务代理

**Comment by 1357310795** [comment]
改了程序里的监听地址吗

**Comment by APORduo** [comment]
> 改了程序里的监听地址吗

并没有更改，所在网络为SJTU-wifi，分配的大子网ip，windows和ubuntu上都存在这个问题

**Comment by 1357310795** [comment]
> 并没有更改

所以要改呀，改成`分配的大子网ip`

**Comment by APORduo** [comment]
> > 并没有更改
> 
> 所以要改呀，改成`分配的大子网ip`

好吧...虽然这样肯定可以，如果能够自动打通就更好了~
thx

**Comment by 1357310795** [comment]
> 自动打通

改成 `http://+:65472/` 可以监听所有连接，但是在Windows上可能有权限问题。所以默认用了127.0.0.1
